# (C) Copyright 2018-2020 Enthought, Inc., Austin, TX
# All rights reserved.
#
# This software is provided without warranty under the terms of the BSD
# license included in LICENSE.txt and may be redistributed only under
# the conditions described in the aforementioned license. The license
# is also available online at http://www.enthought.com/licenses/BSD.txt
#
# Thanks for using Enthought open source!

name: 'Enthought Deployment Manager (EDM) Setup'
description: 'Install and setup EDM static binaries'
author: 'Enthought'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  edm-version:
    description: 'EDM version required'
    required: true
  download-directory:
    description: 'Directory for storing the downloaded EDM installer(s).'
    required: false
    default: ~/.cache/download

runs:
  using: 'node12'
  main: 'dist/index.js'
