name: CI

on: pull_request

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install EDM
        uses: ./
        with:
          edm-version: 4.1.0
      - name: Show EDM versions
        run: edm versions
